### ISSUE TITLE
register_as  variable for loop actions

### ISSUE THREAD

**Issue by vjsaisha** [CiscoDevNet/FMCAnsible#12]
When we are adding the objects through the **loop** function and using the **register_as** function it's not holding all the objects attributes only the last execution item is only holding.  

Any way to achieve this?

**Comment by vjsaisha** [comment]
`- hosts: all
  connection: httpapi
  vars:
    src_obj_host: 
	  - 10.1.1.1
	  - 10.1.1.2
	dst_obj_host:
	  - 10.2.1.1
  tasks:
    - name: Get Domain UUID
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain


#### 1 Get network domain
	- name: Get Domain UUID
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
      register_as: domain


#### 2 Create network object Host Type

### 2a. Create network object host type by upsert
    - name: Create a network object type - Host
      cisco.fmcansible.fmc_configuration:
        operation: upsertHostObject
        data:
          name: 'IP-{{item}}'
          value: '{{item}}'
          type: Host
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
        register_as: networkobjectcreated
      loop: '{{ src_obj_host + dst_obj_host }}'
`

**Comment by b1r63r** [comment]
Hopefully you have your answer a long time ago, but try the following
```
   - name: Create a network object type - Host
     cisco.fmcansible.fmc_configuration:
        operation: upsertHostObject
        data:
          name: 'IP-{{item}}'
          value: '{{item}}'
          type: Host
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
      register: networkobjectcreated
      loop: '{{ src_obj_host + dst_obj_host }}'
```
That is move the register_as in the module data to register at the task level.
