### ISSUE TITLE
Creating host objects doesn't appear to work?

### ISSUE THREAD

**Issue by ibplayn** [CiscoDevNet/FMCAnsible#55]
Has anyone successfully created host objects with this repo? I cannot seem to get creating host objects to work.
FMC version 7.2.4
Playbook:
````
---
- name: Firepower - Create Host Object
   hosts: firepower
   connection: httpapi
   tasks:
      - name: Get Domain UUID
         cisco.fmcansible.fmc_configuration:
            operation: getAllDomain
            register_as: domain

      - name: Create Network Object
         cisco.fmcansible.fmc_configuration:
             operation: createMultipleNetworkObject
             data:
              - name: "testhostname"
                value: "10.10.10.10"
                type: Host
              path_params:
                 domainUUID: '{{ domain[0].uuid }}'
````

Error:
`fatal: [firewall.example.com]: FAILED! => {"changed": false, "msg": "Server returned an error trying to execute createMultipleNetwork operation. Status code: 400. Server Response: Input type mismatch. You have entered an invalid value 10.10.10.10 for selected type Network."}`

Perhaps I am not specifying the correct type, or using the wrong syntax but I have tried multiple variations with no success.
