### ISSUE TITLE
FMC Ansible Module ignores proxy settings – cannot reach FMC in proxied environments

### ISSUE THREAD

**Issue by BMWfan** [CiscoDevNet/FMCAnsible#74]
Hello,

we encountered a blocking issue when trying to use the `cisco.fmcansible.fmc_configuration` module in a proxied enterprise environment.

❗ Problem Summary:
The FMC Ansible module appears to **bypass proxy environment** variables such as `http_proxy` and `https_proxy`, even when explicitly set. This results in timeouts when attempting to access FMC via `httpapi` connection, especially in environments where direct internet or internal access is restricted and must go through a proxy.

This was confirmed through traffic captures during a support session with Cisco TAC. Their recommendation was to open this issue here in the DevNet repository, as the behavior lies outside the support scope of TAC.

🔁 Reproduction Steps:
```
- name: Get Domain UUID
  cisco.fmcansible.fmc_configuration:
    operation: getAllDomain
    register_as: domain
  environment:
    http_proxy: http://my.proxy:80
    https_proxy: http://my.proxy:80
```

```
- name: Get Domain UUID
  cisco.fmcansible.fmc_configuration:
    operation: getAllDomain
    register_as: domain
  vars:
    http_proxy: http://my.proxy:80
    https_proxy: http://my.proxy:80
```
Expected: The module should respect the proxy settings and connect successfully.
Actual: The connection times out and fails with a ConnectionError due to direct access attempts.

🔍 Environment:
Ansible version: 2.14.6

FMC version: 760113.0.0

OS: Debian 11

Module version: 1.0.4

Proxy type: HTTP (optionally via corkscrew)

🧩 Request:
Please confirm if proxy support is implemented at all. If not, this is a critical feature request to support standard enterprise network configurations. Proxy support is essential in environments where no direct internet or cross-network access is permitted.

We would greatly appreciate guidance, a workaround, or timeline for proxy support in this module.

Thank you!
